ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 171000 --common-object-size 512' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 148000 --common-object-size 1024' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 94000 --common-object-size 2048' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 53000 --common-object-size 4096' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 23000 --common-object-size 8192' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 9000 --common-object-size 16384' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 2500 --common-object-size 32768' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv

ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 171000 --common-object-size 512' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 148000 --common-object-size 1024' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 94000 --common-object-size 2048' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 53000 --common-object-size 4096' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 23000 --common-object-size 8192' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 9000 --common-object-size 16384' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 2500 --common-object-size 32768' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv

ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 171000 --common-object-size 512' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 148000 --common-object-size 1024' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 94000 --common-object-size 2048' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 53000 --common-object-size 4096' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 23000 --common-object-size 8192' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 9000 --common-object-size 16384' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 2500 --common-object-size 32768' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv

ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 171000 --common-object-size 512' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 148000 --common-object-size 1024' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 94000 --common-object-size 2048' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 53000 --common-object-size 4096' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 23000 --common-object-size 8192' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 9000 --common-object-size 16384' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 2500 --common-object-size 32768' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv

ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 171000 --common-object-size 512' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 148000 --common-object-size 1024' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 94000 --common-object-size 2048' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 53000 --common-object-size 4096' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 23000 --common-object-size 8192' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 9000 --common-object-size 16384' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv
ansible-playbook experiment.yml -e "extra_args='--client-req-per-sec 2500 --common-object-size 32768' input_file=benchmark/exp-object-size/workload-s1.0 config_file=benchmark/exp-object-size/config.toml output_dir=benchmark/exp-object-size/results" -vv